
package com.qlpk.ui;  
  
import com.qlpk.utils.Auth;
import com.qlpk.utils.XImage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar; 
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import net.miginfocom.swing.MigLayout;


public class QLPhongKhamDaKhoa extends javax.swing.JFrame {

    /**
     * Creates new form QLPhongKhamDaKhoa
     */
    public QLPhongKhamDaKhoa() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Phòng Khám Đa Khoa");
        this.setIconImage(XImage.getAppIcon());
        inti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChinh = new javax.swing.JPanel();
        pnlChucNang = new javax.swing.JPanel();
        pnlBenhNhan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlColorBenhNhan = new javax.swing.JPanel();
        pnlPhieuKham = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlcolorPhieuKham = new javax.swing.JPanel();
        pnlDonThuoc = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlcolorDonThuoc = new javax.swing.JPanel();
        pnlThuoc = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlcolorThuoc = new javax.swing.JPanel();
        pnlNhanVien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlcolorNhanVien = new javax.swing.JPanel();
        pnlDichvu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlcolorHome = new javax.swing.JPanel();
        pnlPhongKham = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlcolorPhongKham = new javax.swing.JPanel();
        pnlTieu = new javax.swing.JPanel();
        lblChucNang = new javax.swing.JLabel();
        pnlFrom = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        pnlFromHome = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lblTill = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblThang = new javax.swing.JLabel();
        lblNam = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();
        lblPhuc = new javax.swing.JLabel();
        lblGiay = new javax.swing.JLabel();
        pnlFromBenhNhan = new javax.swing.JPanel();
        pnlFromPhieuKham = new javax.swing.JPanel();
        pnlFromPhongKham = new javax.swing.JPanel();
        pnlFromDonThuoc = new javax.swing.JPanel();
        pnlFromThuoc = new javax.swing.JPanel();
        pnlFromNhanVien = new javax.swing.JPanel();
        pnlFromGioiThieu = new javax.swing.JPanel();
        pnlFromThongKe = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangxuat = new javax.swing.JButton();
        btnDoiPass = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnGioiThieu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlChinh.setBackground(new java.awt.Color(255, 255, 255));

        pnlChucNang.setBackground(new java.awt.Color(65, 3, 88));

        pnlBenhNhan.setBackground(new java.awt.Color(160, 126, 173));
        pnlBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBenhNhanMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bệnh Nhân");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/patient.png"))); // NOI18N

        pnlColorBenhNhan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlColorBenhNhanLayout = new javax.swing.GroupLayout(pnlColorBenhNhan);
        pnlColorBenhNhan.setLayout(pnlColorBenhNhanLayout);
        pnlColorBenhNhanLayout.setHorizontalGroup(
            pnlColorBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlColorBenhNhanLayout.setVerticalGroup(
            pnlColorBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBenhNhanLayout = new javax.swing.GroupLayout(pnlBenhNhan);
        pnlBenhNhan.setLayout(pnlBenhNhanLayout);
        pnlBenhNhanLayout.setHorizontalGroup(
            pnlBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBenhNhanLayout.createSequentialGroup()
                .addComponent(pnlColorBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBenhNhanLayout.setVerticalGroup(
            pnlBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBenhNhanLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20))
            .addComponent(pnlColorBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPhieuKham.setBackground(new java.awt.Color(160, 126, 173));
        pnlPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPhieuKhamMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Phiếu Khám");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/PhieuKham.png"))); // NOI18N

        pnlcolorPhieuKham.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlcolorPhieuKhamLayout = new javax.swing.GroupLayout(pnlcolorPhieuKham);
        pnlcolorPhieuKham.setLayout(pnlcolorPhieuKhamLayout);
        pnlcolorPhieuKhamLayout.setHorizontalGroup(
            pnlcolorPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlcolorPhieuKhamLayout.setVerticalGroup(
            pnlcolorPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPhieuKhamLayout = new javax.swing.GroupLayout(pnlPhieuKham);
        pnlPhieuKham.setLayout(pnlPhieuKhamLayout);
        pnlPhieuKhamLayout.setHorizontalGroup(
            pnlPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhieuKhamLayout.createSequentialGroup()
                .addComponent(pnlcolorPhieuKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPhieuKhamLayout.setVerticalGroup(
            pnlPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhieuKhamLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(pnlcolorPhieuKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlDonThuoc.setBackground(new java.awt.Color(160, 126, 173));
        pnlDonThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDonThuocMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Đơn Thuốc");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/DonThuoc.png"))); // NOI18N

        pnlcolorDonThuoc.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlcolorDonThuocLayout = new javax.swing.GroupLayout(pnlcolorDonThuoc);
        pnlcolorDonThuoc.setLayout(pnlcolorDonThuocLayout);
        pnlcolorDonThuocLayout.setHorizontalGroup(
            pnlcolorDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlcolorDonThuocLayout.setVerticalGroup(
            pnlcolorDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDonThuocLayout = new javax.swing.GroupLayout(pnlDonThuoc);
        pnlDonThuoc.setLayout(pnlDonThuocLayout);
        pnlDonThuocLayout.setHorizontalGroup(
            pnlDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDonThuocLayout.createSequentialGroup()
                .addComponent(pnlcolorDonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDonThuocLayout.setVerticalGroup(
            pnlDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonThuocLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(pnlcolorDonThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlThuoc.setBackground(new java.awt.Color(160, 126, 173));
        pnlThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlThuocMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Thuốc");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/thuoc.png"))); // NOI18N

        pnlcolorThuoc.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlcolorThuocLayout = new javax.swing.GroupLayout(pnlcolorThuoc);
        pnlcolorThuoc.setLayout(pnlcolorThuocLayout);
        pnlcolorThuocLayout.setHorizontalGroup(
            pnlcolorThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlcolorThuocLayout.setVerticalGroup(
            pnlcolorThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlThuocLayout = new javax.swing.GroupLayout(pnlThuoc);
        pnlThuoc.setLayout(pnlThuocLayout);
        pnlThuocLayout.setHorizontalGroup(
            pnlThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThuocLayout.createSequentialGroup()
                .addComponent(pnlcolorThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlThuocLayout.setVerticalGroup(
            pnlThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThuocLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(pnlcolorThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNhanVien.setBackground(new java.awt.Color(160, 126, 173));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNhanVienMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nhân Viên");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/NhanVien.png"))); // NOI18N

        pnlcolorNhanVien.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlcolorNhanVienLayout = new javax.swing.GroupLayout(pnlcolorNhanVien);
        pnlcolorNhanVien.setLayout(pnlcolorNhanVienLayout);
        pnlcolorNhanVienLayout.setHorizontalGroup(
            pnlcolorNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlcolorNhanVienLayout.setVerticalGroup(
            pnlcolorNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addComponent(pnlcolorNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(pnlcolorNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlDichvu.setBackground(new java.awt.Color(153, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 36, 246));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dịch Vụ & Chức Nặng");

        javax.swing.GroupLayout pnlDichvuLayout = new javax.swing.GroupLayout(pnlDichvu);
        pnlDichvu.setLayout(pnlDichvuLayout);
        pnlDichvuLayout.setHorizontalGroup(
            pnlDichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        pnlDichvuLayout.setVerticalGroup(
            pnlDichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        pnlHome.setBackground(new java.awt.Color(160, 126, 173));
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHomeMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Home");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/home.png"))); // NOI18N

        pnlcolorHome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlcolorHomeLayout = new javax.swing.GroupLayout(pnlcolorHome);
        pnlcolorHome.setLayout(pnlcolorHomeLayout);
        pnlcolorHomeLayout.setHorizontalGroup(
            pnlcolorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlcolorHomeLayout.setVerticalGroup(
            pnlcolorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addComponent(pnlcolorHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
            .addComponent(pnlcolorHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPhongKham.setBackground(new java.awt.Color(160, 126, 173));
        pnlPhongKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPhongKhamMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Phòng Khám");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/phongkham.png"))); // NOI18N

        pnlcolorPhongKham.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlcolorPhongKhamLayout = new javax.swing.GroupLayout(pnlcolorPhongKham);
        pnlcolorPhongKham.setLayout(pnlcolorPhongKhamLayout);
        pnlcolorPhongKhamLayout.setHorizontalGroup(
            pnlcolorPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlcolorPhongKhamLayout.setVerticalGroup(
            pnlcolorPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPhongKhamLayout = new javax.swing.GroupLayout(pnlPhongKham);
        pnlPhongKham.setLayout(pnlPhongKhamLayout);
        pnlPhongKhamLayout.setHorizontalGroup(
            pnlPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhongKhamLayout.createSequentialGroup()
                .addComponent(pnlcolorPhongKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPhongKhamLayout.setVerticalGroup(
            pnlPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhongKhamLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnlPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
            .addComponent(pnlcolorPhongKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBenhNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPhieuKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDonThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPhongKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlDichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPhieuKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPhongKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTieu.setBackground(new java.awt.Color(207, 81, 255));

        lblChucNang.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblChucNang.setForeground(new java.awt.Color(229, 248, 4));
        lblChucNang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucNang.setText("Home");

        javax.swing.GroupLayout pnlTieuLayout = new javax.swing.GroupLayout(pnlTieu);
        pnlTieu.setLayout(pnlTieuLayout);
        pnlTieuLayout.setHorizontalGroup(
            pnlTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTieuLayout.setVerticalGroup(
            pnlTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlFrom.setBackground(new java.awt.Color(15, 14, 14));
        pnlFrom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabs.setOpaque(true);

        pnlFromHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/Doingu.jpg"))); // NOI18N

        lblTill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTill.setForeground(new java.awt.Color(0, 102, 255));
        lblTill.setText("Phòng Khám Đa Khoa Y Tâm Cúc");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Ngày");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Tháng");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Năm");

        lblNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(255, 0, 141));
        lblNgay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgay.setText("01");

        lblThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThang.setForeground(new java.awt.Color(255, 0, 141));
        lblThang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThang.setText("01");

        lblNam.setBackground(new java.awt.Color(204, 204, 204));
        lblNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNam.setForeground(new java.awt.Color(255, 0, 141));
        lblNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNam.setText("2020");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Giờ");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Phúc");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Giây");

        lblGio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGio.setForeground(new java.awt.Color(255, 0, 141));
        lblGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio.setText("00");

        lblPhuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhuc.setForeground(new java.awt.Color(255, 0, 141));
        lblPhuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhuc.setText("00");

        lblGiay.setBackground(new java.awt.Color(204, 204, 204));
        lblGiay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGiay.setForeground(new java.awt.Color(255, 0, 141));
        lblGiay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGiay.setText("00");

        javax.swing.GroupLayout pnlFromHomeLayout = new javax.swing.GroupLayout(pnlFromHome);
        pnlFromHome.setLayout(pnlFromHomeLayout);
        pnlFromHomeLayout.setHorizontalGroup(
            pnlFromHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFromHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTill, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(pnlFromHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFromHomeLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNam)
                        .addContainerGap(192, Short.MAX_VALUE))
                    .addGroup(pnlFromHomeLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGiay)
                        .addGap(135, 135, 135))))
            .addGroup(pnlFromHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFromHomeLayout.setVerticalGroup(
            pnlFromHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFromHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addGroup(pnlFromHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFromHomeLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTill, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFromHomeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlFromHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(lblNgay)
                            .addComponent(lblThang)
                            .addComponent(lblNam))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFromHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(lblGio)
                            .addComponent(lblPhuc)
                            .addComponent(lblGiay))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tabs.addTab("tab1", pnlFromHome);

        pnlFromBenhNhan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromBenhNhanLayout = new javax.swing.GroupLayout(pnlFromBenhNhan);
        pnlFromBenhNhan.setLayout(pnlFromBenhNhanLayout);
        pnlFromBenhNhanLayout.setHorizontalGroup(
            pnlFromBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromBenhNhanLayout.setVerticalGroup(
            pnlFromBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab2", pnlFromBenhNhan);

        pnlFromPhieuKham.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromPhieuKhamLayout = new javax.swing.GroupLayout(pnlFromPhieuKham);
        pnlFromPhieuKham.setLayout(pnlFromPhieuKhamLayout);
        pnlFromPhieuKhamLayout.setHorizontalGroup(
            pnlFromPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromPhieuKhamLayout.setVerticalGroup(
            pnlFromPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab3", pnlFromPhieuKham);

        pnlFromPhongKham.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromPhongKhamLayout = new javax.swing.GroupLayout(pnlFromPhongKham);
        pnlFromPhongKham.setLayout(pnlFromPhongKhamLayout);
        pnlFromPhongKhamLayout.setHorizontalGroup(
            pnlFromPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromPhongKhamLayout.setVerticalGroup(
            pnlFromPhongKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab4", pnlFromPhongKham);

        pnlFromDonThuoc.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromDonThuocLayout = new javax.swing.GroupLayout(pnlFromDonThuoc);
        pnlFromDonThuoc.setLayout(pnlFromDonThuocLayout);
        pnlFromDonThuocLayout.setHorizontalGroup(
            pnlFromDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromDonThuocLayout.setVerticalGroup(
            pnlFromDonThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab5", pnlFromDonThuoc);

        pnlFromThuoc.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromThuocLayout = new javax.swing.GroupLayout(pnlFromThuoc);
        pnlFromThuoc.setLayout(pnlFromThuocLayout);
        pnlFromThuocLayout.setHorizontalGroup(
            pnlFromThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromThuocLayout.setVerticalGroup(
            pnlFromThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab6", pnlFromThuoc);

        pnlFromNhanVien.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromNhanVienLayout = new javax.swing.GroupLayout(pnlFromNhanVien);
        pnlFromNhanVien.setLayout(pnlFromNhanVienLayout);
        pnlFromNhanVienLayout.setHorizontalGroup(
            pnlFromNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromNhanVienLayout.setVerticalGroup(
            pnlFromNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab7", pnlFromNhanVien);

        pnlFromGioiThieu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromGioiThieuLayout = new javax.swing.GroupLayout(pnlFromGioiThieu);
        pnlFromGioiThieu.setLayout(pnlFromGioiThieuLayout);
        pnlFromGioiThieuLayout.setHorizontalGroup(
            pnlFromGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromGioiThieuLayout.setVerticalGroup(
            pnlFromGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab8", pnlFromGioiThieu);

        pnlFromThongKe.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFromThongKeLayout = new javax.swing.GroupLayout(pnlFromThongKe);
        pnlFromThongKe.setLayout(pnlFromThongKeLayout);
        pnlFromThongKeLayout.setHorizontalGroup(
            pnlFromThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        pnlFromThongKeLayout.setVerticalGroup(
            pnlFromThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        tabs.addTab("tab9", pnlFromThongKe);

        pnlFrom.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -35, 990, 640));

        javax.swing.GroupLayout pnlChinhLayout = new javax.swing.GroupLayout(pnlChinh);
        pnlChinh.setLayout(pnlChinhLayout);
        pnlChinhLayout.setHorizontalGroup(
            pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChinhLayout.createSequentialGroup()
                .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlChinhLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(pnlTieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChinhLayout.setVerticalGroup(
            pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChinhLayout.createSequentialGroup()
                .addComponent(pnlTieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(new java.awt.Color(0, 255, 230));
        jToolBar1.setRollover(true);

        btnDangxuat.setBackground(new java.awt.Color(0, 255, 230));
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/Log out.png"))); // NOI18N
        btnDangxuat.setText("Đăng Xuất");
        btnDangxuat.setFocusable(false);
        btnDangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangxuat);

        btnDoiPass.setBackground(new java.awt.Color(0, 255, 230));
        btnDoiPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/Key.png"))); // NOI18N
        btnDoiPass.setText("Đổi Mật Khẩu");
        btnDoiPass.setFocusable(false);
        btnDoiPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiPass.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiPassActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDoiPass);

        btnThongKe.setBackground(new java.awt.Color(0, 255, 230));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/Dollar.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        btnGioiThieu.setBackground(new java.awt.Color(0, 255, 230));
        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlpk/icon/Globe.png"))); // NOI18N
        btnGioiThieu.setText("Giới Thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private MigLayout layout;
    
    private QLBenhNhan qLBenhNhan;
    private QLPhieuKham qLPhieuKham;
    private QLPhongKham qLPhongKham;
    private QLDonThuoc qLDonThuoc;
    private QLThuoc qLThuoc;
    private QLNhanVien qLNhanVien;
    private GioiThieu gioiThieu;
    private QLThongKe qLThongKe;
    

    
    void inti(){
        this.setColor(pnlcolorHome,pnlHome); // discoloration
        this.reserColor(new JPanel[]{pnlColorBenhNhan,pnlcolorPhieuKham,pnlcolorPhongKham,pnlcolorDonThuoc,pnlcolorThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlBenhNhan,pnlPhieuKham,pnlPhongKham,pnlDonThuoc,pnlThuoc,pnlNhanVien}); // reser color
        tabs.setSelectedIndex(0);
        lblChucNang.setText("Home");
        this.GetDate();
        //setExtendedState(JFrame.MAXIMIZED_BOTH); 
        
        layout = new MigLayout();
        pnlFromBenhNhan.setLayout(layout);
        pnlFromPhieuKham.setLayout(layout);
        pnlFromPhongKham.setLayout(layout);
        pnlFromDonThuoc.setLayout(layout);
        pnlFromThuoc.setLayout(layout);
        pnlFromNhanVien.setLayout(layout);
        pnlFromGioiThieu.setLayout(layout);
        pnlFromThongKe.setLayout(layout);
        
        qLBenhNhan = new QLBenhNhan();
        qLPhieuKham = new QLPhieuKham();
        qLPhongKham = new QLPhongKham();
        qLDonThuoc = new QLDonThuoc();
        qLThuoc = new QLThuoc();
        qLNhanVien = new QLNhanVien();
        gioiThieu = new GioiThieu();
        qLThongKe = new QLThongKe();
    }
    
    void setColor(JPanel pane,JPanel indicators){
        pane.setBackground(new Color(14,227,250));
        indicators.setBackground(new Color(222,175,239));
    }
    
    void reserColor(JPanel [] pane, JPanel [] indicators){
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(255,255,255));
        }
        
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setBackground(new Color(160,126,173));
        }
    }
    
    void GetDate (){
        Calendar cal = Calendar.getInstance();
        // hiển thị ngày tháng năm
        int Ngay =cal.get(Calendar.DAY_OF_MONTH);
        int Thang =(cal.get(Calendar.MONTH)+1);
        int Nam =cal.get(Calendar.YEAR);
        lblNgay.setText(String.valueOf(Ngay));
        lblThang.setText(String.valueOf(Thang));
        lblNam.setText(String.valueOf(Nam));
        
        // hiển thị giờ hiện tại   
        new Timer(1000, new ActionListener() {
            SimpleDateFormat Hour = new SimpleDateFormat("hh");
            SimpleDateFormat Minite = new SimpleDateFormat("mm");
            SimpleDateFormat sdf = new SimpleDateFormat("ss");
            @Override
            public void actionPerformed(ActionEvent e) {
                lblGio.setText(Hour.format(new Date()));
                lblPhuc.setText(Minite.format(new Date()));
                lblGiay.setText(sdf.format(new Date()));
            }
        }).start();
    }

    private void pnlHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMousePressed
        // TODO add your handling code here:
        this.setColor(pnlcolorHome,pnlHome); // discoloration
        this.reserColor(new JPanel[]{pnlColorBenhNhan,pnlcolorPhieuKham,pnlcolorPhongKham,pnlcolorDonThuoc,pnlcolorThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlBenhNhan,pnlPhieuKham,pnlPhongKham,pnlDonThuoc,pnlThuoc,pnlNhanVien}); // reser color
        tabs.setSelectedIndex(0);
        lblChucNang.setText("Home");
        this.GetDate();
    }//GEN-LAST:event_pnlHomeMousePressed

    private void pnlBenhNhanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBenhNhanMousePressed
        // TODO add your handling code here:
        this.setColor(pnlColorBenhNhan,pnlBenhNhan);// discoloration
        this.reserColor(new JPanel[]{pnlcolorHome,pnlcolorPhieuKham,pnlcolorPhongKham,pnlcolorDonThuoc,pnlcolorThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlHome,pnlPhieuKham,pnlPhongKham,pnlDonThuoc,pnlThuoc,pnlNhanVien});// reser color
        tabs.setSelectedIndex(1);
        lblChucNang.setText("Bệnh Nhân");
        pnlFromBenhNhan.add(qLBenhNhan);
    }//GEN-LAST:event_pnlBenhNhanMousePressed

    private void pnlPhieuKhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPhieuKhamMousePressed
        // TODO add your handling code here:
        this.setColor(pnlcolorPhieuKham,pnlPhieuKham);// discoloration
        this.reserColor(new JPanel[]{pnlcolorHome,pnlColorBenhNhan,pnlcolorPhongKham,pnlcolorDonThuoc,pnlcolorThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlHome,pnlBenhNhan ,pnlPhongKham,pnlDonThuoc,pnlThuoc,pnlNhanVien});// reser color
        tabs.setSelectedIndex(2);
        lblChucNang.setText("Phiếu Khám");
        pnlFromPhieuKham.add(qLPhieuKham);
    }//GEN-LAST:event_pnlPhieuKhamMousePressed

    private void pnlPhongKhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPhongKhamMousePressed
        // TODO add your handling code here:
        this.setColor(pnlcolorPhongKham,pnlPhongKham);// discoloration
        this.reserColor(new JPanel[]{pnlcolorHome,pnlColorBenhNhan,pnlcolorPhieuKham,pnlcolorDonThuoc,pnlcolorThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlHome,pnlBenhNhan ,pnlPhieuKham,pnlDonThuoc,pnlThuoc,pnlNhanVien});// reser color
        tabs.setSelectedIndex(3);
        lblChucNang.setText("Phòng Khám");
        pnlFromPhongKham.add(qLPhongKham);
    }//GEN-LAST:event_pnlPhongKhamMousePressed

    private void pnlDonThuocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDonThuocMousePressed
        // TODO add your handling code here:
        this.setColor(pnlcolorDonThuoc,pnlDonThuoc);// discoloration
        this.reserColor(new JPanel[]{pnlcolorHome,pnlColorBenhNhan,pnlcolorPhieuKham,pnlcolorPhongKham,pnlcolorThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlHome,pnlBenhNhan ,pnlPhieuKham,pnlPhongKham,pnlThuoc,pnlNhanVien});// reser color
        tabs.setSelectedIndex(4);
        lblChucNang.setText("Đơn Thuốc");
        pnlFromDonThuoc.add(qLDonThuoc);
    }//GEN-LAST:event_pnlDonThuocMousePressed
  
    private void pnlThuocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThuocMousePressed
        // TODO add your handling code here:
        this.setColor(pnlcolorThuoc,pnlThuoc);// discoloration
        this.reserColor(new JPanel[]{pnlcolorHome,pnlColorBenhNhan,pnlcolorPhieuKham,pnlcolorPhongKham,pnlcolorDonThuoc,pnlcolorNhanVien}, 
                new JPanel[]{pnlHome,pnlBenhNhan ,pnlPhieuKham,pnlDonThuoc,pnlPhongKham,pnlNhanVien});// reser color
        tabs.setSelectedIndex(5);
        lblChucNang.setText("Thuốc");
        pnlFromThuoc.add(qLThuoc);
    }//GEN-LAST:event_pnlThuocMousePressed

    private void pnlNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMousePressed
        // TODO add your handling code here:
        this.setColor(pnlcolorNhanVien,pnlNhanVien);// discoloration
        this.reserColor(new JPanel[]{pnlcolorHome,pnlColorBenhNhan,pnlcolorPhieuKham,pnlcolorPhongKham,pnlcolorDonThuoc,pnlcolorThuoc}, 
                new JPanel[]{pnlBenhNhan ,pnlPhieuKham,pnlDonThuoc,pnlPhongKham,pnlThuoc,pnlThuoc});// reser color
        tabs.setSelectedIndex(6);
        lblChucNang.setText("Nhân Viên");
        pnlFromNhanVien.add(qLNhanVien);
    }//GEN-LAST:event_pnlNhanVienMousePressed

    
    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
        new DangNhapJDialong(Auth.user.getMaNV()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnDoiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiPassActionPerformed
        // TODO add your handling code here:
        new DoiPassJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnDoiPassActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
        tabs.setSelectedIndex(7);
        lblChucNang.setText("Giới Thiệu");
        pnlFromGioiThieu.add(gioiThieu);
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        tabs.setSelectedIndex(8);
        lblChucNang.setText("Thống Kê");
        pnlFromThongKe.add(qLThongKe);
    }//GEN-LAST:event_btnThongKeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhongKhamDaKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhongKhamDaKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhongKhamDaKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhongKhamDaKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLPhongKhamDaKhoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnDoiPass;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblGiay;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblPhuc;
    private javax.swing.JLabel lblThang;
    private javax.swing.JLabel lblTill;
    private javax.swing.JPanel pnlBenhNhan;
    private javax.swing.JPanel pnlChinh;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlColorBenhNhan;
    private javax.swing.JPanel pnlDichvu;
    private javax.swing.JPanel pnlDonThuoc;
    private javax.swing.JPanel pnlFrom;
    private javax.swing.JPanel pnlFromBenhNhan;
    private javax.swing.JPanel pnlFromDonThuoc;
    private javax.swing.JPanel pnlFromGioiThieu;
    private javax.swing.JPanel pnlFromHome;
    private javax.swing.JPanel pnlFromNhanVien;
    private javax.swing.JPanel pnlFromPhieuKham;
    private javax.swing.JPanel pnlFromPhongKham;
    private javax.swing.JPanel pnlFromThongKe;
    private javax.swing.JPanel pnlFromThuoc;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlPhieuKham;
    private javax.swing.JPanel pnlPhongKham;
    private javax.swing.JPanel pnlThuoc;
    private javax.swing.JPanel pnlTieu;
    private javax.swing.JPanel pnlcolorDonThuoc;
    private javax.swing.JPanel pnlcolorHome;
    private javax.swing.JPanel pnlcolorNhanVien;
    private javax.swing.JPanel pnlcolorPhieuKham;
    private javax.swing.JPanel pnlcolorPhongKham;
    private javax.swing.JPanel pnlcolorThuoc;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
